FROM library/node

MAINTAINER Christian Gripp <mail@core23.de>

RUN npm install -g bower grunt-cli

# ADD .bowerrc     /data/.bowerrc
# ADD package.json /data/package.json
# ADD Gruntfile.js /data/Gruntfile.js

WORKDIR /data
